### ISSUE TITLE
还有登录用户时提示 jscode失效

### ISSUE THREAD

**Issue by qc1932647581** [nnkwrik/weapp-fangxianyu#3]
还有登录用户时提示 jscode失效
想问下 这是原因？

_Originally posted by @Rlxzmdd in https://github.com/nnkwrik/weapp-fangxianyu/issues/2#issuecomment-485768974_

**Comment by qc1932647581** [comment]
求请教登录问题怎么解决呢

**Comment by Rlxzmdd** [comment]
我估计你没有填写这一块

## 前端

然而并不能快速开始，首先你得有小程序的appid。需要先申请小程序账号和下载小程序开发工具，步骤可以参考[官方教程](https://developers.weixin.qq.com/miniprogram/dev/)。注册完成后会拿到appid和secret，在`auth-service/src/main/resources/application.yml`中配置你的appid和secret。

```yml
#写入你的小程序信息
wx:
  miniapp:
    appid:  #微信小程序的appid
    secret: #微信小程序的Secret
    msgDataFormat: JSON
```

打开刚下载好的小程序开发工具，创建一个新项目。然后把[wx-front](https://github.com/nnkwrik/fangxianyu/tree/master/wx-front)中的所有文件覆盖到你刚创建的小程序项目目录中。由于小程序默认服务端只能是HTTPS并且是ICP备案过的域名，不方便开发，在小程序开发工具的`设置/项目设置`中把`不校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书`勾上。
